src/ConferenceSchedulerBundle/Entity/Conference.php
<?php

namespace ConferenceSchedulerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Conference
 *
 * @ORM\Table(name="conference")
 * @ORM\Entity(repositoryClass="ConferenceSchedulerBundle\Repository\ConferenceRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Conference {

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var int
     *
     * @ORM\Column(name="access", type="smallint", nullable=true)
     */
    private $access;

    /**
     * @var int
     *
     * @ORM\Column(name="price", type="decimal", precision=7, scale=2, nullable=true)
     * @Assert\NotBlank()
     */
    private $price;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    private $date;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated", type="datetime")
     */
    private $updated;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deleted", type="datetime", nullable=true)
     */
    private $deleted;

    /**
     * @var \ConferenceSchedulerBundle\Entity\Hall
     * , inversedBy="products"
     * 
     * @ORM\ManyToOne(targetEntity="ConferenceSchedulerBundle\Entity\Hall")
     * @ORM\JoinColumn(name="hall_id", referencedColumnName="id")
     * @Assert\NotBlank()
     */
    private $hall;

    /**
     * @var \ConferenceSchedulerBundle\Entity\ConferenceProgram[]
     * 
     * @ORM\OneToMany(targetEntity="ConferenceSchedulerBundle\Entity\ConferenceProgram", mappedBy="conference", cascade={"persist"})
     * @ORM\OrderBy({"start"="ASC"})
     */
    private $programs;

    /**
     * @var \ConferenceSchedulerBundle\Entity\ConferenceLecturer[]
     * 
     * @ORM\OneToMany(targetEntity="ConferenceSchedulerBundle\Entity\ConferenceLecturer", mappedBy="conference", cascade={"persist"})
     * @ORM\OrderBy({"user"="ASC"})
     */
    private $lecturers;

    /**
     * @var \ConferenceSchedulerBundle\Entity\ConferenceAdmin[]
     * 
     * @ORM\OneToMany(targetEntity="ConferenceSchedulerBundle\Entity\ConferenceAdmin", mappedBy="conference", cascade={"persist", "remove"})
     * @ORM\OrderBy({"user"="ASC"})
     */
    private $admins;

    /**
     * @var \ConferenceSchedulerBundle\Entity\ConferenceUser[]
     * 
     * @ORM\OneToMany(targetEntity="ConferenceSchedulerBundle\Entity\ConferenceUser", mappedBy="conference", cascade={"persist"})
     * @ORM\OrderBy({"user"="ASC"})
     */
    private $users;

    /**
     * Construct
     */
    public function __construct() {
        $this->created = new DateTime;
        $this->updated = new DateTime;
        $this->admins = new ArrayCollection;
        $this->lecturers = new ArrayCollection;
        $this->programs = new ArrayCollection;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preStore() {
        $this->updated = new DateTime;
    }

    /**
     * Get access with name
     * 
     * @return string
     */
    public function getAccessName() {
        $name = '';

        switch ($this->access) {
            case 1:
                $name = 'Open';
                break;
            case 2:
                $name = 'Particular';
                break;
        }

        return $name;
    }

    /**
     * Program start
     * 
     * @return \DateTime|null
     */
    public function getProgramStart() {
        $time = null;
        $event = $this->getPrograms()->first();

        if ($event) {
            $time = $event->getStart();
        }

        return $time;
    }

    /**
     * Program end
     * 
     * @return \DateTime|null
     */
    public function getProgramEnd() {
        $time = null;
        $event = $this->getPrograms()->last();

        if ($event) {
            $time = $event->getEnd();
        }

        return $time;
    }

    /**
     * Is conference has dismissed
     * 
     * @return bool
     */
    public function isDeleted() {
        $result = $this->deleted !== null ? true : false;

        return $result;
    }

    /*
     * 
     * Auto generated
     * 
     */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Conference
     */
    public function setTitle($title) {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Conference
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Set access
     *
     * @param integer $access
     *
     * @return Conference
     */
    public function setAccess($access) {
        $this->access = $access;

        return $this;
    }

    /**
     * Get access
     *
     * @return integer
     */
    public function getAccess() {
        return $this->access;
    }

    /**
     * Set price
     *
     * @param string $price
     *
     * @return Conference
     */
    public function setPrice($price) {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return string
     */
    public function getPrice() {
        return $this->price;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Conference
     */
    public function setDate($date) {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate() {
        return $this->date;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Conference
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return Conference
     */
    public function setUpdated($updated) {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated() {
        return $this->updated;
    }

    /**
     * Set deleted
     *
     * @param \DateTime $deleted
     *
     * @return Conference
     */
    public function setDeleted($deleted) {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * Get deleted
     *
     * @return \DateTime
     */
    public function getDeleted() {
        return $this->deleted;
    }

    /**
     * Set hall
     *
     * @param \ConferenceSchedulerBundle\Entity\Hall $hall
     *
     * @return Conference
     */
    public function setHall(\ConferenceSchedulerBundle\Entity\Hall $hall = null) {
        $this->hall = $hall;

        return $this;
    }

    /**
     * Get hall
     *
     * @return \ConferenceSchedulerBundle\Entity\Hall
     */
    public function getHall() {
        return $this->hall;
    }

    /**
     * Add program
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceProgram $program
     *
     * @return Conference
     */
    public function addProgram(\ConferenceSchedulerBundle\Entity\ConferenceProgram $program) {
        $this->programs[] = $program;

        return $this;
    }

    /**
     * Remove program
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceProgram $program
     */
    public function removeProgram(\ConferenceSchedulerBundle\Entity\ConferenceProgram $program) {
        $this->programs->removeElement($program);
    }

    /**
     * Get programs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPrograms() {
        return $this->programs;
    }

    /**
     * Add lecturer
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceLecturer $lecturer
     *
     * @return Conference
     */
    public function addLecturer(\ConferenceSchedulerBundle\Entity\ConferenceLecturer $lecturer) {
        $this->lecturers[] = $lecturer;

        return $this;
    }

    /**
     * Remove lecturer
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceLecturer $lecturer
     */
    public function removeLecturer(\ConferenceSchedulerBundle\Entity\ConferenceLecturer $lecturer) {
        $this->lecturers->removeElement($lecturer);
    }

    /**
     * Get lecturers
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLecturers() {
        return $this->lecturers;
    }

    /**
     * Add admin
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceAdmin $admin
     *
     * @return Conference
     */
    public function addAdmin(\ConferenceSchedulerBundle\Entity\ConferenceAdmin $admin) {
        $this->admins[] = $admin;

src/ConferenceSchedulerBundle/Entity/ConferenceProgram.php
<?php

namespace ConferenceSchedulerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ConferenceProgram
 *
 * @ORM\Table(name="conference_program")
 * @ORM\Entity(repositoryClass="ConferenceSchedulerBundle\Repository\ConferenceProgramRepository")
 */
class ConferenceProgram {

    const TYPE_LECTURE = 1;
    const TYPE_BREAK = 2;
    const TYPES = [
        'Lecture' => self::TYPE_LECTURE,
        'Break' => self::TYPE_BREAK,
    ];

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="start", type="time", nullable=true)
     */
    private $start;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="end", type="time", nullable=true)
     */
    private $end;

    /**
     * @var int
     *
     * @ORM\Column(name="type", type="smallint")
     */
    private $type;

    /**
     * @var \ConferenceSchedulerBundle\Entity\ConferenceProgramLecturer[]
     * 
     * @ORM\OneToMany(targetEntity="ConferenceSchedulerBundle\Entity\ConferenceProgramLecturer", mappedBy="program", cascade={"persist", "remove"})
     * @ORM\OrderBy({"mustVisit"="DESC"})
     */
    private $lecturers;

    /**
     * @var \ConferenceSchedulerBundle\Entity\Conference
     * 
     * @ORM\ManyToOne(targetEntity="ConferenceSchedulerBundle\Entity\Conference", inversedBy="programs")
     * @ORM\JoinColumn(name="conference_id", referencedColumnName="id")
     */
    private $conference;

    /**
     * Constructor
     */
    public function __construct() {
        $this->lecturers = new ArrayCollection;
        $this->type = static::TYPE_LECTURE;
    }

    /**
     * Is it event is a break
     * 
     * @return bool
     */
    public function isBreak() {
        $result = $this->type === static::TYPE_BREAK;
        
        return $result;
    }

    /**
     * Get array of lecturers names
     * 
     * @return array
     */
    public function getLecturersList() {
        $names = [];

        foreach ($this->getLecturers() as $lecturer) {
            $names[] = $lecturer->getUser()->getNames();
        }

        return $names;
    }

    /**
     * Get type like string
     * 
     * @return string
     */
    public function getTypeName() {
        $name = '';

        switch ($this->type) {
            case static::TYPE_LECTURE:
                $name = 'Lecture';
                break;
            case static::TYPE_BREAK:
                $name = 'Break';
                break;
        }

        return $name;
    }

    /*
     * 
     * Auto generated
     * 
     */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return ConferenceProgram
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return ConferenceProgram
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Set start
     *
     * @param \DateTime $start
     *
     * @return ConferenceProgram
     */
    public function setStart($start) {
        $this->start = $start;

        return $this;
    }

    /**
     * Get start
     *
     * @return \DateTime
     */
    public function getStart() {
        return $this->start;
    }

    /**
     * Set end
     *
     * @param \DateTime $end
     *
     * @return ConferenceProgram
     */
    public function setEnd($end) {
        $this->end = $end;

        return $this;
    }

    /**
     * Get end
     *
     * @return \DateTime
     */
    public function getEnd() {
        return $this->end;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return ConferenceProgram
     */
    public function setType($type) {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType() {
        return $this->type;
    }

    /**
     * Set conference
     *
     * @param \ConferenceSchedulerBundle\Entity\Conference $conference
     *
     * @return ConferenceProgram
     */
    public function setConference(\ConferenceSchedulerBundle\Entity\Conference $conference = null) {
        $this->conference = $conference;

        return $this;
    }

    /**
     * Get conference
     *
     * @return \ConferenceSchedulerBundle\Entity\Conference
     */
    public function getConference() {
        return $this->conference;
    }

    /**
     * Add lecturer
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceProgramLecturer $lecturer
     *
     * @return ConferenceProgram
     */
    public function addLecturer(\ConferenceSchedulerBundle\Entity\ConferenceProgramLecturer $lecturer) {
        $this->lecturers[] = $lecturer;

        return $this;
    }

    /**
     * Remove lecturer
     *
     * @param \ConferenceSchedulerBundle\Entity\ConferenceProgramLecturer $lecturer
     */
    public function removeLecturer(\ConferenceSchedulerBundle\Entity\ConferenceProgramLecturer $lecturer) {
        $this->lecturers->removeElement($lecturer);
    }

    /**
     * Get lecturers
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLecturers() {
        return $this->lecturers;
    }

}

src/ConferenceSchedulerBundle/Resources/views/PublicConference/index.html.twig
{% extends "::base.html.twig" %}

{% block title %}
    {{ 'Conferences'|trans }}
{% endblock %}

{% block layout_title %}
    {{ 'Conferences'|trans }}
{% endblock %}

{% block body %}
    <div class="mdl-grid">
        {% for conference in pagination %}
            <div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp">{# portfolio-card mdl-shadow--4dp #}
                <div class="mdl-card__media">
                    <img class="article-image" src="{{ conference.image }}" border="0" height="200" alt="{{ conference.title|e }}">
                </div>
                <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">{{ conference.title }}</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    {% if conference.programStart %}
                        {{ '%date% starts at %start% ends at %end%'|trans({ '%date%': conference.date|date('M d'), '%start%': conference.programStart|date('H:i'), '%end%': conference.programEnd|date('H:i') }) }}
                    {% else %}
                        {{ conference.date|date('M d') }}
                    {% endif %}
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" style="float: right" href="{{ path('public_conference_show', { 'id': conference.id }) }}">{{ 'More'|trans }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/ConferenceSchedulerBundle/Resources/views/PublicConference/schedule.html.twig
{% extends "::base.html.twig" %}

{% block title %}ConferenceSchedulerBundle:Security:login{% endblock %}

{% block body %}
    {#% for conference in conferences %}
        <div class="mdl-card mdl-cell mdl-cell--12-col mdl-shadow--4dp mdl-color-text--grey-800">
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">{{ conference.title }}</h2>
            </div>
            <div class="mdl-card__supporting-text">
                {{ conference.description|nl2br }}
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="portfolio-example01.html">Read more</a>
            </div>
        </div>
    {% endfor %#}
{% endblock %}

src/ConferenceSchedulerBundle/Resources/views/PublicConference/show.html.twig
{% extends "::base.html.twig" %}

{% block title %}
    {{ conference.title }}
{% endblock %}

{% block layout_title %}
    {{ 'Conference'|trans }}
{% endblock %}

{% block layout_ribbon %}
    {{ conference.image }}
{% endblock %}

{% block body %}
    <h3 style="margin: 20px 20px">{{ conference.title }} </h3>
    
    <p style="margin: 0 20px">
        <i class="mdl-color-text--primary">
            {% if conference.programStart %}
            {{ '%date% starts at %start% ends at %end%'|trans({ '%date%': conference.date|date('M d'), '%start%': conference.programStart|date('H:i'), '%end%': conference.programEnd|date('H:i') }) }}
        {% else %}
            {{ conference.date|date('M d') }}
        {% endif %}
        </i>
    </p>
{#    <img class="article-image" src="{{ conference.image }}" border="0" width="100%" alt="{{ conference.title|e }}"/>#}

    {% if conference.programs|length > 0 %}
        <div class="mdl-list">
            <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                    <h5 id="program">{{ 'Program'|trans }}</h5>
                </span>
            </div>
            {% for event in conference.programs %}
                <div class="mdl-list__item mdl-list__item--three-line">
                    <span class="mdl-list__item-primary-content">
                        <span>
                            {{ event.start|date('H:i') }}-{{ event.end|date('H:i') }}
                            {% if event.isBreak %} <i class="mdl-color-text--accent">({{ 'break'|trans }})</i>{% endif %}
                        </span>
                        <span class="mdl-list__item-text-body">
                            {{ event.name }}
                            {% if event.lecturers|length > 0 %} ({{ event.lecturersList|join(', ') }}){% endif %}
                        </span>
                    </span>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <p style="margin: 0 20px">{{ conference.description|nl2br }}</p>

    {% if joined == null %}
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--6-col">
                <h5>{{ 'Price: %price%'|trans({ '%price%': conference.price }) }}</h5>
            </div>
            <div class="mdl-cell mdl-cell--6-col">
                <a href="{{ path('public_conference_join', { 'id': conference.id }) }}" style="float: right" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-color--primary mdl-color-text--white">{{ 'Join'|trans }}</a>
            </div>
        </div>
    {% else %}
        <h5 style="text-align: center" class="mdl-color-text--accent">{{ 'You have joined'|trans }}</h5>
    {% endif %}

    {% if conference.hall %}
        <div class="mdl-list">
            <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                    <h4 id="hall">{{ 'Hall'|trans }} {{ totalUsers }}/{{ conference.hall.userLimit }}</h4>
                </span>
            </div>
            {% set hall = conference.hall %}
            <div class="mdl-list__item mdl-list__item--three-line">
                <span class="mdl-list__item-primary-content">
                    {% if hall.image %}
                        <img src="{{ hall.image }}" class="mdl-list__item-avatar" alt="{{ hall.name|e }}">
                    {% endif %}
                    <span>{{ hall.name }}</span>
                    <span class="mdl-list__item-text-body">
                        {{ hall.venue.address }}
                    </span>
                </span>
            </div>
        </div>
    {% endif %}

    {% if conference.hall.goods|length > 0 %}
        <div class="mdl-list">
            <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                    <h4 id="goods">{{ 'Goods'|trans }}</h4>
                </span>
            </div>
            <div class="mdl-grid">
                {% for good in conference.hall.goods %}
                    <div class="mdl-list__item mdl-cell--6-col">
                        <span class="mdl-list__item-primary-content">
                            <span>
                                <i class="material-icons mdl-list__item-avatar">{{ good.name|replace({ ' ': '_' }) }}</i>
                                {{ good.name }}
                            </span>
                        </span>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if conference.lecturers|length > 0 %}
        <div class="mdl-list">
            <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                    <h4 id="lecturer">{{ 'Lecturer'|trans }}</h4>
                </span>
            </div>
            <div class="mdl-grid">
                {% for lecturer in conference.lecturers %}
                    {% if lecturer.isActive %}
                        {% set user = lecturer.user %}
                        <div class="mdl-cell--6-col mdl-list__item mdl-list__item--three-line">
                            <span class="mdl-list__item-primary-content">
                                {% if user.gravatar %}
                                    <img src="{{ user.gravatar(40) }}" class="mdl-list__item-avatar" alt="{{ user.names|e }}">
                                {% else %}
                                    <i class="material-icons mdl-list__item-avatar">person</i>
                                {% endif %}
                                <span>{{ user.names }}</span>
                            </span>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}