src/ConferenceSchedulerBundle/Entity/ConferenceUser.php
<?php

namespace ConferenceSchedulerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ConferenceLecturer
 *
 * @ORM\Table(name="conference_user")
 * @ORM\Entity(repositoryClass="ConferenceSchedulerBundle\Repository\ConferenceUserRepository")
 */
class ConferenceUser {

    /**
     * User is successfully joined to the conference
     */
    const STATUS_ACTIVE = 1;

    /**
     * System wait user to pay for conference
     */
    const STATUS_PENDING = 2;

    /**
     * The user will not visit the conference
     */
    const STATUS_REFUSED = 3;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \ConferenceSchedulerBundle\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="ConferenceSchedulerBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @var \ConferenceSchedulerBundle\Entity\Conference
     * 
     * @ORM\ManyToOne(targetEntity="ConferenceSchedulerBundle\Entity\Conference", inversedBy="users")
     * @ORM\JoinColumn(name="conference_id", referencedColumnName="id")
     */
    private $conference;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="smallint")
     */
    private $status;

    // @todo add relation to payment transaction

    /**
     * Construct
     */
    public function __construct() {
        $this->status = static::STATUS_ACTIVE;
    }

    /**
     * Get status name
     * 
     * @return string
     */
    public function getStatusName() {
        $name = '';

        switch ($this->status) {
            case static::STATUS_ACTIVE:
                $name = 'Active';
                break;
            case static::STATUS_PENDING:
                $name = 'Pending';
                break;
            case static::STATUS_REFUSED:
                $name = 'Refused';
                break;
        }

        return $name;
    }

    /*
     * 
     * Auto generated
     * 
     */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return ConferenceUser
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set user
     *
     * @param \ConferenceSchedulerBundle\Entity\User $user
     *
     * @return ConferenceUser
     */
    public function setUser(\ConferenceSchedulerBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \ConferenceSchedulerBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set conference
     *
     * @param \ConferenceSchedulerBundle\Entity\Conference $conference
     *
     * @return ConferenceUser
     */
    public function setConference(\ConferenceSchedulerBundle\Entity\Conference $conference = null)
    {
        $this->conference = $conference;

        return $this;
    }

    /**
     * Get conference
     *
     * @return \ConferenceSchedulerBundle\Entity\Conference
     */
    public function getConference()
    {
        return $this->conference;
    }
}

src/ConferenceSchedulerBundle/Controller/ConferenceUserController.php
<?php

namespace ConferenceSchedulerBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use ConferenceSchedulerBundle\Entity\Conference;
use ConferenceSchedulerBundle\Entity\ConferenceUser;
use ConferenceSchedulerBundle\Entity\User;
use ConferenceSchedulerBundle\Event\ConferenceEvent;

/**
 * Conference users controller.
 *
 * @Route("conference/{conference_id}/users")
 */
class ConferenceUserController extends Controller {

    /**
     * Lists all conference entities.
     *
     * @Route("/", name="conference_user_index")
     * @Method("GET")
     * @Template()
     * @ParamConverter("conference", class="ConferenceSchedulerBundle:Conference", options={"id"="conference_id"})
     */
    public function indexAction(Conference $conference) {
        $totalUsers = $this->getDoctrine()
                ->getManager()
                ->getRepository('ConferenceSchedulerBundle:ConferenceUser')
                ->countByConference($conference);

        return [
            'conference' => $conference,
            'totalUsers' => $totalUsers,
        ];
    }

    /**
     * Lists all users that not add to conference
     *
     * @Route("/invite", name="conference_user_invite")
     * @Method("GET")
     * @Template()
     * @ParamConverter("conference", class="ConferenceSchedulerBundle:Conference", options={"id"="conference_id"})
     */
    public function inviteAction(Request $request, Conference $conference) {
        $query = $this->getDoctrine()
                ->getManager()
                ->getRepository('ConferenceSchedulerBundle:User')
                ->findNotUserOrLecturerInConferenceQuery($conference);

        $pagination = $this->get('knp_paginator')
                ->paginate($query, $request->query->getInt('page', 1))
        ;


        return [
            'conference' => $conference,
            'pagination' => $pagination,
        ];
    }

    /**
     * Add user to conference
     *
     * @Route("/{id}/add", name="conference_user_add")
     * @Method("GET")
     * @Template()
     * @ParamConverter("conference", class="ConferenceSchedulerBundle:Conference", options={"id"="conference_id"})
     */
    public function addAction(Conference $conference, User $user) {
        $em = $this->getDoctrine()->getManager();

        $limit = $conference->getHall()->getUserLimit();
        $totalUsers = $em->getRepository('ConferenceSchedulerBundle:ConferenceUser')
                ->countByConference($conference);

        // check for user limit of hall
        if ($totalUsers >= $limit) {
            $this->addFlash('notice', 'You have reached the limit of the hall');

            goto redirectToList;
        }

        $conferenceUser = new ConferenceUser;
        $conferenceUser->setConference($conference);
        $conferenceUser->setUser($user);

        $conference->addUser($conferenceUser);

        $em->flush();

        // dispatch event
        $event = new ConferenceEvent($conference, $user);
        $this->get('event_dispatcher')
                ->dispatch(ConferenceEvent::EVENT_USER_ADD, $event);

        // flashbag
        $this->addFlash('notice', 'User has been add to the conference');

        redirectToList: {
            return $this->redirectToRoute('conference_user_invite', [
                        'conference_id' => $conference->getId(),
            ]);
        }
    }

    /**
     * Remove user from conference
     *
     * @Route("/{id}/remove", name="conference_user_remove")
     * @Method("GET")
     * @Template()
     * @ParamConverter("conference", class="ConferenceSchedulerBundle:Conference", options={"id"="conference_id"})
     */
    public function removeAction(Conference $conference, User $user) {
        $em = $this->getDoctrine()->getManager();

        // find relation lecture with conference
        $conferenceUser = $em->getRepository('ConferenceSchedulerBundle:ConferenceUser')
                ->findOneBy([
            'conference' => $conference,
            'user' => $user,
        ]);

        if ($conferenceUser === null) {
            goto redirectToList;
        }

        $em->remove($conferenceUser);
        $em->flush();

        // dispatch event
        $event = new ConferenceEvent($conference, $user);
        $this->get('event_dispatcher')
                ->dispatch(ConferenceEvent::EVENT_USER_DELETE, $event);

        // flashbag
        $this->addFlash('notice', 'User has been removed from conference');

        redirectToList: {
            return $this->redirectToRoute('conference_user_index', [
                        'conference_id' => $conference->getId(),
            ]);
        }
    }

}

src/ConferenceSchedulerBundle/Resources/views/ConferenceUser/index.html.twig
{% extends 'base.html.twig' %}

{% block layout_title %}
    {{ 'Conference users'|trans }}
{% endblock %}

{% block header %}
    {% include 'ConferenceSchedulerBundle:Conference:tabs.html.twig' with {'conference': conference, 'active': 'users'} %}
{% endblock %}

{% block body %}
    <section class="mdl-layout__tab-panel is-active">
        <div class="mdl-list">
            <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                    <span>
                        <h6>{{ 'Joined users'|trans }} ({{ totalUsers }}/{{ conference.hall.userLimit }})</h6>
                    </span>
                </span>
                <span class="mdl-list__item-secondary-content">
                    <a id="user-add" class="mdl-list__item-secondary-action" href="{{ path('conference_user_invite', { 'conference_id': conference.id }) }}">
                        <i class="material-icons">group_add</i>
                    </a>
                    <div class="mdl-tooltip" data-mdl-for="user-add">
                        {{ 'Add users to the conference'|trans }}
                    </div>
                </span>
            </div>
            {% for confUser in conference.users %}
                {% set user = confUser.user %}
                <div class="mdl-list__item mdl-list__item--three-line">
                    <span class="mdl-list__item-primary-content">
                        {% if user.gravatar %}
                            <img src="{{ user.gravatar(40) }}" class="mdl-list__item-avatar" alt="{{ user.names|e }}">
                        {% else %}
                            <i class="material-icons mdl-list__item-avatar">person</i>
                        {% endif %}
                        <span>{{ user.names }}</span>
                        <span class="mdl-list__item-text-body">
                            {{ confUser.statusName }}
                        </span>
                    </span>
                    <a class="mdl-list__item-secondary-action" href="{{ path('conference_user_remove', { 'conference_id': conference.id, 'id': user.id }) }}">
                        <i class="material-icons">clear</i>
                    </a>
                </div>
            {% endfor %}
    </section>
{% endblock %}

src/ConferenceSchedulerBundle/Resources/views/ConferenceUser/invite.html.twig
{% extends 'base.html.twig' %}

{% block layout_title %}
    {{ 'Add users to conference'|trans }}
{% endblock %}

{% block header %}
    {% include 'ConferenceSchedulerBundle:Conference:tabs.html.twig' with {'conference': conference, 'active': 'users'} %}
{% endblock %}

{% block body %}
    <section class="mdl-layout__tab-panel is-active">
        <div class="mdl-list">
            <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                    <span>
                        <h6>{{ 'Users'|trans }}</h6>
                    </span>
                </span>
            </div>
            {% for user in pagination %}
                <div class="mdl-list__item mdl-list__item--three-line">
                    <span class="mdl-list__item-primary-content">
                        {% if user.gravatar %}
                            <img src="{{ user.gravatar(40) }}" class="mdl-list__item-avatar" alt="{{ user.names|e }}">
                        {% else %}
                            <i class="material-icons mdl-list__item-avatar">person</i>
                        {% endif %}
                        <span>{{ user.names }}</span>
                        <span class="mdl-list__item-text-body">
                            {{ user.email }}
                        </span>
                    </span>
                    <span class="mdl-list__item-secondary-content">
                        <a id="user-add-{{ user.id }}" class="mdl-list__item-secondary-action" href="{{ path('conference_user_add', { 'conference_id': conference.id, 'id': user.id }) }}" class="mdl-button mdl-js-button">
                            <i class="material-icons">person_add</i>
                        </a>
                        <div class="mdl-tooltip" data-mdl-for="user-add-{{ user.id }}">
                            {{ 'Add user to conference'|trans }}
                        </div>
                    </span>
                </div>
            {% endfor %}
        </div>
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </section>
{% endblock %}